name: CI/CD StudyProject-AuthServer

on:
  push:
    branches: [ "main" ]

jobs:
  CI-CD:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
  
      - name: Gradlew permission
        run: chmod +x gradlew
  
      - name: Build with Gradle
        run: ./gradlew clean build
  
      - name: Make Directory
        run: mkdir dist
  
      - name: Copy jar
        run: cp ./build/libs/*.jar ./dist/
  
      - name: zip
        run: tar -zcvf deploy.tar.gz ./dist
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
  
      - name: Upload to ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 569790459761.dkr.ecr.ap-northeast-2.amazonaws.com \
          docker build -t study-auth . \
          docker tag study-auth:latest 569790459761.dkr.ecr.ap-northeast-2.amazonaws.com/study-auth:latest \
          docker push 569790459761.dkr.ecr.ap-northeast-2.amazonaws.com/study-auth:latest
